import Navbar from "@/components/navbar"

export default function TermsOfServicePage() {
    return (
        <div className="min-h-screen bg-gray-50">
            <Navbar />
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
                <h1 className="text-3xl font-bold text-gray-900 mb-8">Terms of Service</h1>

                <div className="prose prose-purple max-w-none bg-white p-8 rounded-lg shadow-sm">
                    <p className="mb-4">Last Updated: {new Date().toLocaleDateString()}</p>

                    <h2 className="text-xl font-semibold mt-6 mb-4">1. Acceptance of Terms</h2>
                    <p>
                        By accessing or using Cuentee, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.
                    </p>

                    <h2 className="text-xl font-semibold mt-6 mb-4">2. Description of Service</h2>
                    <p>
                        Cuentee is an AI-powered platform that allows users to generate personalized stories and images.
                    </p>

                    <h2 className="text-xl font-semibold mt-6 mb-4">3. User Accounts</h2>
                    <p>
                        You are responsible for maintaining the confidentiality of your account capabilities and for all activities that occur under your account.
                    </p>

                    <h2 className="text-xl font-semibold mt-6 mb-4">4. Content Generation</h2>
                    <p>
                        You retain ownership of the prompts you input. We assign to you all rights, title, and interest in the outputs generated by the service based on your prompts,
                        subject to the terms of the underlying AI models.
                    </p>

                    <h2 className="text-xl font-semibold mt-6 mb-4">5. Use Restrictions</h2>
                    <p>
                        You agree not to use the service to generate content that is harmful, offensive, illegal, or infringes on the rights of others.
                    </p>

                    <h2 className="text-xl font-semibold mt-6 mb-4">6. Changes to Terms</h2>
                    <p>
                        We adhere to the right to modify these terms at any time. We will notify you of any material changes by posting the new Terms of Service on this page.
                    </p>
                </div>
            </div>
        </div>
    )
}
