"use client"

import { useState } from "react"
import { ChevronDown, ChevronUp } from "lucide-react"
import { Card, CardContent } from "@/components/ui/card"

import Link from "next/link"
import React from "react"

interface FAQItem {
  question: string
  answer: React.ReactNode
}

const faqData: FAQItem[] = [
  {
    question: "How does Cuentee work?",
    answer:
      "Cuentee uses advanced AI technology to generate personalized stories based on your prompts. Simply describe what kind of story you'd like, and our AI will create a unique, child-friendly tale in seconds. You can specify characters, settings, themes, and more to make each story special.",
  },
  {
    question: "Is the content safe for children?",
    answer:
      "All stories generated by Cuentee are designed to be age-appropriate, educational, and safe for children. Our AI is trained to create positive, uplifting content that promotes good values, creativity, and learning. We continuously monitor and improve our content filters to ensure the highest safety standards.",
  },
  {
    question: "What's included in the free trial?",
    answer:
      "The free trial includes one sample story so you can experience the magic of Cuentee. You'll have access to basic story templates, our child-friendly interface, and can see how easy it is to create personalized tales. No credit card required to start!",
  },
  {
    question: "How does the Pay as You Go plan work?",
    answer:
      "For $10, you get 10 story credits that never expire. Each time you generate a story, one credit is used. You can purchase additional credits anytime you need them. This plan includes advanced AI features, custom character creation, story saving, and priority support.",
  },
  {
    question: "Can I save and share the stories?",
    answer:
      "Yes! With the Pay as You Go plan, you can save all your generated stories to your account and share them with family and friends. Stories are stored securely in your personal library, and you can access them anytime from any device.",
  },
  {
    question: "What age groups are the stories suitable for?",
    answer:
      "Cuentee stories are designed for children ages 3-12, but can be enjoyed by the whole family! You can specify the reading level and complexity when creating your story prompt to ensure it's perfect for your child's age and comprehension level.",
  },
  {
    question: "Can I customize characters and settings?",
    answer:
      "You can create stories with custom characters, settings, and themes. Want a story about a brave princess and her pet dragon in a magical forest? Or perhaps a tale about a young astronaut exploring distant planets? Just describe your vision, and our AI will bring it to life.",
  },
  {
    question: "Do I need to download any software?",
    answer:
      "No downloads required! Cuentee works entirely in your web browser on any device - computer, tablet, or smartphone. Just log in to your account and start creating stories instantly.",
  },
  {
    question: "What if I'm not satisfied with a story?",
    answer:
      "We offer a 30-day satisfaction guarantee. If you're not happy with your stories, contact our support team for a full refund. We're also constantly improving our AI, and you can always regenerate a story with a different prompt if the first version isn't quite right.",
  },
  {
    question: "How long are the generated stories?",
    answer:
      "Stories typically range from 200-800 words, perfect for bedtime reading or short attention spans. The length can vary based on your prompt complexity and the story elements you request. Most stories take 2-5 minutes to read aloud.",
  },
  {
    question: "Can I use Cuentee for educational purposes?",
    answer:
      "Yes! Cuentee is perfect for educators, homeschooling parents, and anyone looking to create educational content. You can generate stories that teach specific lessons, incorporate learning objectives, or explore particular themes and values.",
  },
  {
    question: "Do you use cookies?",
    answer: (
      <>
        Yes, we use cookies to ensure you get the best experience on our website. For detailed information about how we use
        cookies, please view our{" "}
        <Link href="/cookie-policy" className="text-purple-600 hover:text-purple-700 underline">
          Cookie Policy
        </Link>
        .
      </>
    ),
  },
  {
    question: "Where can I find your Privacy Policy?",
    answer: (
      <>
        Your privacy is our priority. You can read our full{" "}
        <Link href="/privacy-policy" className="text-purple-600 hover:text-purple-700 underline">
          Privacy Policy
        </Link>{" "}
        to understand how we collect, use, and protect your data.
      </>
    ),
  },
  {
    question: "What are the Terms of Service?",
    answer: (
      <>
        By using Cuentee, you agree to our{" "}
        <Link href="/terms-of-service" className="text-purple-600 hover:text-purple-700 underline">
          Terms of Service
        </Link>
        . Please read them carefully to understand your rights and responsibilities.
      </>
    ),
  },
]

export default function FAQSection() {
  const [openItems, setOpenItems] = useState<number[]>([])

  const toggleItem = (index: number) => {
    setOpenItems((prev) => (prev.includes(index) ? prev.filter((i) => i !== index) : [...prev, index]))
  }

  return (
    <div className="space-y-4">
      {faqData.map((item, index) => (
        <Card key={index} className="overflow-hidden">
          <button
            onClick={() => toggleItem(index)}
            className="w-full text-left p-6 hover:bg-gray-50 transition-colors focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-inset"
          >
            <div className="flex justify-between items-center">
              <h3 className="text-lg font-semibold text-gray-900 pr-4">{item.question}</h3>
              {openItems.includes(index) ? (
                <ChevronUp className="h-5 w-5 text-purple-600 flex-shrink-0" />
              ) : (
                <ChevronDown className="h-5 w-5 text-purple-600 flex-shrink-0" />
              )}
            </div>
          </button>

          {openItems.includes(index) && (
            <CardContent className="pt-0 pb-6">
              <div className="border-t pt-4">
                <div className="text-gray-600 leading-relaxed">{item.answer}</div>
              </div>
            </CardContent>
          )}
        </Card>
      ))}
    </div>
  )
}
