FROM python:3.11-slim
WORKDIR /app

# Copy requirements first
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory (.) into /app/api
COPY . ./api/

# Set PYTHONPATH to /app so python can find the 'api' package
ENV PYTHONPATH=/app

# Run celery worker
CMD ["celery", "-A", "api.tasks", "worker", "--loglevel=info"]